### ISSUE TITLE
没有 Gruntfile.js 或者 Gruntfile.coffee 的情况下会报错

### ISSUE THREAD

**Issue by vvtommy** [fordlee404/generator-webapp-kit#2]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
AssertionError: /Users/vvtommy/development/work/magicbox/app_store/Gruntfile.js doesn't exist
    at EditionInterface.module.exports [as read] (/Users/vvtommy/development/sharing/tools/generator-fordlee404/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at Base.Object.defineProperty.get (/Users/vvtommy/development/sharing/tools/generator-fordlee404/node_modules/yeoman-generator/lib/base.js:161:33)
    at module.exports.yeoman.generators.Base.extend.writing.gruntfile (/Users/vvtommy/development/sharing/tools/generator-fordlee404/app/index.js:189:11)
    at /Users/vvtommy/development/sharing/tools/generator-fordlee404/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by fordlee404** [comment]
Fixed it on `develop` branch

**Comment by vvtommy** [comment]
修复之后，就不创建 Gruntfile 了

**Comment by fordlee404** [comment]
fixed it
